### ISSUE TITLE
`DisplayHex` impls have different behaviours for different types 

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/hex-conservative#83]
`DisplayArray`, `DisplayByteSlice`, and `fmt_hex_exact` each behave differently, this is surprising.

For example, how they handle `Formatter::precision`.

**Comment by tankyleo** [comment]
Part of the reason is that `DisplayArray::display` and `DisplayByteSlice::display` are currently different implementations.

One possible solution could be to have 
```
fn internal_display(bytes: &[u8], f: &mut fmt::Formatter, case: Case) -> fmt::Result;
```
and both of these structs would call this internal function.

Then to have a single implementation that is also used for `fmt_hex_exact`, we could rewrite `internal_display` in terms of a `T: IntoIterator`, instead of a `&[u8]`, with possibly the help of the `ExactSizeIterator` bound.

Thank you for your input.

**Comment by tcharding** [comment]
This issue looks like it is almost done.

> Then to have a single implementation that is also used for fmt_hex_exact, we could rewrite internal_display in terms of a T: IntoIterator, instead of a &[u8], with possibly the help of the ExactSizeIterator bound.

This sounds correct. Do you want to work on it?

I hacked the `test_display_hex` macro to try to verify exactly what was currently now working, here it is if you want to use it. It could do with cleaning up though.

```diff
diff --git a/src/display.rs b/src/display.rs
index 9dce504..dcf8221 100644
--- a/src/display.rs
+++ b/src/display.rs
@@ -534,6 +534,7 @@ where
             encoder.as_str()
         }
     };
+
     f.pad_integral(true, "0x", encoded)
 }
 
@@ -643,12 +644,54 @@ mod tests {
             assert_eq!(format!("{:.65}", dummy), "2a".repeat(32));
         }
 
+        struct Dummy2([u8; 2]);
+        impl fmt::Display for Dummy2 {
+            fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+                fmt_hex_exact!(f, 2, &self.0, Case::Lower)
+            }
+        }
+        struct Dummy4([u8; 4]);
+        impl fmt::Display for Dummy4 {
+            fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+                fmt_hex_exact!(f, 4, &self.0, Case::Lower)
+            }
+        }
+        struct Dummy512([u8; 512]);
+        impl fmt::Display for Dummy512 {
+            fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
+                fmt_hex_exact!(f, 512, &self.0, Case::Lower)
+            }
+        }
+
         macro_rules! test_display_hex {
             ($fs: expr, $a: expr, $check: expr) => {
-                let to_display_array = $a;
-                let to_display_byte_slice = Vec::from($a);
-                assert_eq!(format!($fs, to_display_array.as_hex()), $check);
-                assert_eq!(format!($fs, to_display_byte_slice.as_hex()), $check);
+                let array = $a;
+                let slice = &$a; // Obviously a byte slice.
+                let vec = Vec::from($a); // Uses `DisplayByteSlice` as well.
+
+                assert_eq!(format!($fs, array.as_hex()), $check);
+                assert_eq!(format!($fs, slice.as_hex()), $check);
+                assert_eq!(format!($fs, vec.as_hex()), $check);
+
+                if array.len() == 2 {
+                    let mut buf: [u8; 2] = [0; 2];
+                    buf.copy_from_slice(slice);
+                    let dummy = Dummy2(buf);
+                    assert_eq!(format!($fs, dummy), $check);
+                } else if array.len() == 4 {
+                    let mut buf: [u8; 4] = [0; 4];
+                    buf.copy_from_slice(slice);
+                    let dummy = Dummy4(buf);
+                    assert_eq!(format!($fs, dummy), $check);
+                } else if array.len() == 512 {
+                    let mut buf: [u8; 512] = [0; 512];
+                    buf.copy_from_slice(slice);
+                    let dummy = Dummy512(buf);
+                    assert_eq!(format!($fs, dummy), $check);
+                } else {
+                    eprintln!("You forgot to implement DummyX for array length: {}", array.len());
+                    panic!();
+                }
             };
         }
```

And running it we get


```bash
failures:

---- display::tests::alloc::precision_with_padding_truncates stdout ----
thread 'display::tests::alloc::precision_with_padding_truncates' panicked at src/display.rs:728:13:
assertion `left == right` failed
  left: "      1234"
 right: "1234      "

---- display::tests::alloc::precision_with_padding_pads_right stdout ----
thread 'display::tests::alloc::precision_with_padding_pads_right' panicked at src/display.rs:734:13:
assertion `left == right` failed
  left: "  12345678"
 right: "12345678  "
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    display::tests::alloc::precision_with_padding_pads_right
    display::tests::alloc::precision_with_padding_truncates

test result: FAILED. 53 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by tcharding** [comment]
I think we should do this for `v1.0`. @apoelstra do you have an opinion?

**Comment by tcharding** [comment]
Legend.

**Comment by apoelstra** [comment]
Agreed we should do this for v1.
